### ISSUE TITLE
[Core] Tree visualisation of Units

### ISSUE THREAD

**Issue by lorderikir** [MonashUnitPlanner/monPlanR#360]
Using d3.js to map out a tree to show what units to take before a unit, something similar to a skill tree.

**Comment by jos0003** [comment]
It's not a tree. It's only a directed acyclic graph, since there are many cases of units which have prerequisites of multiple units (and some do not have prohibitions that prevent students from doing both/all of those prerequisite units).

(Maybe it could contain cycles after all, and what we have is just a graph. It doesn't make sense to have a graph of units that has a cycle in them, but it would be interesting to find a case where there is one).

# TODO

- [ ] Pan and zoom for easier navigation
- [ ] Use HTML elements for units by using `foreignObject`s in SVG
- [ ] Add links if a unit is a prereq/coreq of another unit in an existing course plan
- [ ] Provide suggestions/recommendations for units after or before other units
- [ ] Find some way to correspond tree representation with original tabular representation (by using the same JSON courseStructure object in localStorage)
